name: Eternity Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - macos-ci
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.3
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true

    - name: Configure CMake
      run: |
        cmake -S . -B build64 -G "Visual Studio 17 2022" -A x64
        cmake -S . -B build32 -G "Visual Studio 17 2022" -A Win32

    - name: Build
      run: |
        cmake --build build64 --config Release
        cmake --build build32 --config Release

    - name: Add text files
      if: github.event_name == 'workflow_dispatch'
      run: |
        Copy-Item COPYING build32/eternity/Release/COPYING.txt
        Copy-Item COPYING-EE build32/eternity/Release/COPYING-EE.txt
        Copy-Item docs/readme.txt "build32/eternity/Release/ee-$(git describe --tags).txt"

        Copy-Item COPYING build64/eternity/Release/COPYING.txt
        Copy-Item COPYING-EE build64/eternity/Release/COPYING-EE.txt
        Copy-Item docs/readme.txt "build64/eternity/Release/ee-$(git describe --tags).txt"

    - name: Archive release build
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v7.0.1
      with:
        name: windows-release
        path: build??/eternity/Release

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - extra-cmake-arg: -DPNG_INTEL_SSE=on
            arch: x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Xcode -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} ${{ matrix.extra-cmake-arg }}

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Sign and notarize the bundle
        uses: ioan-chera/action-macos-sign-notarize@v1.3
        with:
          certificate: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.MACOS_P12_PASSWORD }}
          username: ${{ secrets.MACOS_NOTARY_USER }}
          password: ${{ secrets.MACOS_NOTARY_PASSWORD }}
          entitlements-path: macosx/eternity/eternity.entitlements
          apple-team-id: ${{ secrets.MACOS_TEAM_ID }}
          app-path: build/macosx/launcher/Release/Eternity Engine.app

      - name: Add text files
        # if: github.event_name == 'workflow_dispatch'
        run: |
          cp COPYING build/macosx/launcher/Release/COPYING.txt
          cp COPYING-EE build/macosx/launcher/Release/COPYING-EE.txt
          cp docs/readme.txt "build/macosx/launcher/Release/ee-$(git describe --tags).txt"

      - name: build DMG
        # if: github.event_name == 'workflow_dispatch'
        run: |
          hdiutil create -srcfolder build/macosx/launcher/Release/ -volname "ee-$(git describe --tags)-${{ matrix.arch }}" -fs HFS+ -format UDZO ee-$(git describe --tags)-${{ matrix.arch }}.dmg

      - name: Archive release build
        # if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: macos-release
          path: "*.dmg"
